version: 2
jobs:
  build:
    working_directory: /go/src/github.com/nickalie/go-binwrapper
    docker:
      - image: golang
    steps:
      - checkout
      - run: go get -t -v ./...
      - run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...
      - run: curl -s https://codecov.io/bash | bash